# pylint: skip-file
# Generated by Django 3.2.16 on 2023-03-22 16:44

from django.db import migrations, models
import django.db.models.deletion
import simple_data_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=simple_data_api.models.generate_api_token, max_length=1048576, unique=True)),
                ('responsible_party', models.CharField(max_length=1048576)),
            ],
        ),
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('request', models.TextField(max_length=1048576)),
                ('errored', models.BooleanField(default=False)),
                ('response', models.TextField(max_length=1048576)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='simple_data_api.apitoken')),
            ],
        ),
    ]
