# pylint: skip-file
# Generated by Django 3.2.21 on 2023-10-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_data_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicall',
            options={'verbose_name': 'API Call', 'verbose_name_plural': 'API Calls'},
        ),
        migrations.AlterModelOptions(
            name='apitoken',
            options={'verbose_name': 'API Token', 'verbose_name_plural': 'API Tokens'},
        ),
    ]
